Repository JGCarmona-Consulting/tfst, pull requests merged in 2024-11, with the labels that each got.

#7 Feature/app service plan dev
  infrastructure/README.md
  infrastructure/envs/dev/env.hcl
  infrastructure/envs/dev/service_plan/terragrunt.hcl
  infrastructure/envs/terragrunt.hcl
  infrastructure/modules/service_plan/main.tf
  infrastructure/modules/service_plan/outputs.tf
  infrastructure/modules/service_plan/variables.tf
  scripts/initialize_azure_backend.sh
  scripts/setup_local_env.sh
Labels: infrastructure

#25 22 fix issues with docker https configuration and project execution
  src/api/TheFullStackTeam.API/Program.cs
  src/api/TheFullStackTeam.API/Properties/launchSettings.json
  src/api/TheFullStackTeam.API/TheFullStackTeam.API.csproj
  src/api/TheFullStackTeam.API/TheFullStackTeam.API.http
  src/api/TheFullStackTeam.API/example.env
  src/api/TheFullStackTeam.Application/Auth/Commands/AuthenticateUser.cs
  src/api/TheFullStackTeam.Application/TheFullStackTeam.Application.csproj
  src/api/docker-compose.override.yml
  src/api/docker-compose.yml
Labels: good first issue

#43 API runs on HTTPS by default and add file README.md with solution for…
  src/api/README.md
  src/api/docker-compose.override.yml
  src/api/docker-compose.yml
Labels: bug, documentation
